name: iOS Development Build J316sAP

on:
  pull_request:
    branches-ignore:
      - 'l10n_main'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_main'
  workflow_dispatch:

jobs:
  build-ios:
    name: Build for iOS
    runs-on: J316sAP

    steps:
      - name: Clean workspace
        run: |
          echo "Cleaning workspace..."
          rm -rf ./* ./.??* || true
          echo "Workspace cleaned."
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get gl4es latest commit hash
        id: gl4es-sha
        run: |
          SHA=$(git ls-remote https://github.com/PojavLauncherTeam/gl4es-114-extra refs/heads/master | cut -f1)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
        shell: bash

      # Download JREs as dependencies
      - name: Download JRE8
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          path: depends
          workflow_conclusion: success
          allow_forks: false
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre8
          name: jre8-ios-aarch64

      - name: Download JRE17
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          path: depends
          workflow_conclusion: completed
          allow_forks: false
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre17-ios-aarch64

      - name: Download JRE21
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          path: depends
          workflow_conclusion: completed
          allow_forks: false
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre21-ios-aarch64

      - name: Build iOS Artifacts
        run: |
          export PATH=/opt/homebrew/bin:$PATH
          export RUNNER=1 SLIMMED=1
          gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=2
          gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=2 TROLLSTORE_JIT_ENT=1
        shell: bash

      # Upload all relevant artifacts
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: org.angelauramc.amethyst-ios.ipa
          path: artifacts/org.angelauramc.amethyst-*-ios.ipa

      - name: Upload TIPA (TrollStore)
        uses: actions/upload-artifact@v4
        with:
          name: org.angelauramc.amethyst-ios-trollstore.tipa
          path: artifacts/org.angelauramc.amethyst-*-ios-trollstore.tipa

      - name: Upload Slimmed IPA
        uses: actions/upload-artifact@v4
        with:
          name: org.angelauramc.amethyst.slimmed-ios.ipa
          path: artifacts/org.angelauramc.amethyst.slimmed-*-ios.ipa

      - name: Upload Slimmed TIPA (TrollStore)
        uses: actions/upload-artifact@v4
        with:
          name: org.angelauramc.amethyst.slimmed-ios-trollstore.tipa
          path: artifacts/org.angelauramc.amethyst.slimmed-*-ios-trollstore.tipa

      - name: Upload dSYM
        uses: actions/upload-artifact@v4
        with:
          name: AngelAuraAmethyst.dSYM
          path: artifacts/AngelAuraAmethyst.dSYM
